### ISSUE TITLE
USER STORY: Create Poll to enhance interativity with members

### ISSUE THREAD

**Issue by Peter-Hennessy** [Peter-Hennessy/My-first-agile-project#3]
In order to **enhance interactions and widen the community ** as an **administrator**, I can ** increase the level of functionality of the site ** through the creation of an anonymous poll

**Comment by Peter-Hennessy** [comment]
## **Acceptance Criteria**

- User should be able to log in and complete the poll anonymously
- There should be an apparent increase in engagement with members 
- All input should be  visibly Implemented to increase the functionality of the site and show acknowledgment of input

**Comment by Peter-Hennessy** [comment]
## **Tasks:**
- [] The poll form should be clear to the user  what is expected
- [] All forms should be Created  in HTML CSS format
- [] The poll should have a function to cease after an allocated period of time
- [] Test Functionality

**Comment by Peter-Hennessy** [comment]
This is completed
